### ISSUE TITLE
[knife-windows master]  winrm bootstrap with --winrm-authentication-protocol negotiate gives HTTP 400 

### ISSUE THREAD

**Issue by siddheshwar-more** [chef/knife-windows#218]
I've used knife-windows master branch and WinRm released version.

knife bootstrap windows winrm - with negotiate authentication protocol i.e --winrm-authentication-protocol negotiate and on remote server allowunencrypted is false. 

I got http error code 400 for above case.
Refer logs- https://gist.github.com/siddheshwar-more/a431d9fbc1c481211f0d

Seems this issue is Due to change in WinRM gem refer-  https://github.com/WinRb/WinRM/pull/134

**Comment by btm** [comment]
https://github.com/WinRb/WinRM/pull/134 was a fix for long running ```knife winrm``` issues, filed as https://github.com/winrb/winrm/issues/129.

@siddheshwar-more could you try to identify the bug in winrm?

**Comment by siddheshwar-more** [comment]
Am looking into 'winrm-s' monkey patch ( i.e supports winrm negotiate auth) . I think we need to update it according to WinRb/WinRM#134 .

**Comment by siddheshwar-more** [comment]
@btm yeah am looking into both side i.e winrm-s and winrm gem.

**Comment by siddheshwar-more** [comment]
@btm @adamedx 

The issue is due to change in winrm gem WinRb/WinRM#134
I've updated 'winrm-s' monkey patch to fix this issue. PR reference- https://github.com/chef/winrm-s/pull/25 

Could you also try this with/without above PR? I tried it at my end and its works fine.

**Comment by btm** [comment]
I was just testing knife-windows 1.0.0.rc.0 and was hitting this again. Or so I thought. I was having inconsistent and time-consuming results.

I'm, still timing out with AllowUnencrypted=true with this error with knife-windows 1.0.0.rc.0, winrm-s 0.3.0, and winrm 1.3.3:

```
Waiting for remote response before bootstrap.......................ERROR: No response received from remote node after 1.86 minutes, giving up.
ERROR: WinRM::WinRMHTTPTransportError: Unable to parse WinRM response: #<ArgumentError: invalid byte sequence in UTF-8>
```

I'm using this command:
```
knife bootstrap windows winrm -x Administrator -t plaintext -p 80 -P 'P@ssw0rd' -N novalidatorforlife --winrm-authentication-protocol negotiate 192.168.5.109
```

Port 80 is because I'm using Server 2008 for the test.

Part of the confusing thing is after I set AllowUnencrypted back to false, I have to restart the WinRM service before it works again.

Did we regress since we confirmed https://github.com/chef/knife-windows/issues/210 was fixed? @smurawski is out sick, so we can't ask him right now.

**Comment by btm** [comment]
Okay, I get the expected error on Server 2012 R2 Standard when AllowUnencrypted=true.

I'm going to presume the 2008 issue is limited to older versions of Windows until someone tells me otherwise.
