### ISSUE TITLE
Catch errors when knife-windows 1.0.0 is used with chefdk version v0.6.* 

### ISSUE THREAD

**Issue by siddheshwar-more** [chef/knife-windows#253]
@btm @adamedx -

Please refer- https://github.com/chef/chef-dk/issues/411#issuecomment-113387016

Here knife-windows 1.0.0.rc.0 has some issues with Chef-dk version '0.6.*'

We are planing to catch and handle this errors in knife-windows and show proper error message like- 'This knife-windows version '1.0.*' won't work with chef-dk below 0.7.0.'

@btm let us know your thought on this issue.

**Comment by adamedx** [comment]
@siddheshwar-more, can you verify that handling this exception is actually possible?

**Comment by siddheshwar-more** [comment]
@adamedx -
`knife windows` -  during command execution it requires file from `chef` and `mixlib::cli`.
And I think its not possible to override few things during load time.

This need monkey patch for chef and `mixlib::cli` and I think applying monkey patches here is dangerous.

**Comment by siddheshwar-more** [comment]
@btm 

We have updated release notes to mention above chef-dk compatibility issue. Please refer - https://github.com/chef/knife-windows/pull/254 

Please let us know your thoughts about this issue.

**Comment by btm** [comment]
Yeah, unfortunately the errors are in rubygems loading, and I don't think we can catch that in knife-windows because knife-windows isn't actually loaded in the case of https://github.com/chef/chef-dk/issues/411#issuecomment-113387016.

We're going to have to live with the release notes caveat, and then get ChefDK 0.7.0 out soon.
