### ISSUE TITLE
Bootstrap appends Chef directory to end of Windows path

### ISSUE THREAD

**Issue by chef09210** [chef/knife-windows#369]
The current bootstrap appends the Chef bin directory to the end of the Windows path, which causes problems when issuing Ruby commands that conflict with other ruby installations such as Cygwin. The added path should be placed in the front rather than end of the environment PATH variable.

**Comment by btm** [comment]
The path is set as part of the installation of the MSI, not by knife-windows.

https://github.com/chef/chef/blob/master/omnibus/resources/chef/msi/source.wxs.erb#L104

I can't find a bug there. You're welcome to open one, but I think we prefer adding to the end of the path so we don't conflict with other parts of your system. Having multiple ruby installations isn't something we can account for consistently because it could be a windows ruby, or cygwin, or something else. Thus it's left to the user to modify the path order if that's what they want.
