### ISSUE TITLE
Add Support for Chef Zero

### ISSUE THREAD

**Issue by ajrkerr** [chef/knife-windows#419]
I would love to be able to use Chef Zero with knife-windows. I know that kitchen-window does this, and I believe that the only piece of missing functionality is uploading the cookbooks using the WinRM library.

Is this something which is on your roadmap, or would you be open to accepting a PR if I put one together?

**Comment by cheeseplus** [comment]
This isn't really a feature that is supportable in the current context - knife is used to bootstrap nodes for use in a chef-client <-> chef-server setup. In theory you could do this via a custom bootstrap template but that's somewhat abusing the design as opposed to using something built for this purpose.

There already exists an implementation of this https://github.com/higanworks/knife-zero. Chef may add support for this kind of workflow in the future but it would not be via knife. Closing this since we don't plan to add this functionality, it already exists in a different place, and this wouldn't be knife-windows specific.
